name: bd_calling_task
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^1.2.2
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.8
  intl: ^0.20.1

dev_dependencies:
  build_runner: ^2.0.0
  hive_generator: ^1.0.0
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
